/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
// Variables for user credentials and file path
public class Update extends javax.swing.JFrame {
    private static String usname, pass, type = "admin";

    private static String filepath = "C:\\Users\\Admin\\Documents\\NetBeansProjects\\AT4_Villacampa(1A)\\src\\data.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cusernamefield = new javax.swing.JTextField();
        Cpasswordfeild = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nuserfeild = new javax.swing.JTextField();
        Npasswordfield = new javax.swing.JTextField();
        Updatebutton = new javax.swing.JButton();
        Clearbutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Cusernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusernamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(Cusernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 244, -1));

        Cpasswordfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpasswordfeildActionPerformed(evt);
            }
        });
        jPanel1.add(Cpasswordfeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 244, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 91, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 91, -1));

        Nuserfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuserfeildActionPerformed(evt);
            }
        });
        jPanel1.add(Nuserfeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 244, -1));

        Npasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NpasswordfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Npasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 244, -1));

        Updatebutton.setText("Update");
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, 50));

        Clearbutton.setText("Clear");
        Clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 50));

        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 105, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\yeha.gif")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Method to handle the Update button click event
    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
        // TODO add your handling code here:
 try {
        filecheck(); // Load existing data

        String currentUsername = Cusernamefield.getText().trim();
        String currentPassword = Cpasswordfeild.getText().trim();
        String newUsername = Nuserfeild.getText().trim();
        String newPassword = Npasswordfield.getText().trim();
        boolean found = false;

        for (int i = 0; i < userlist.size(); i++) {
            JSONObject user = (JSONObject) userlist.get(i);
            
            if (user.get("username").equals(currentUsername) && user.get("password").equals(currentPassword)) {
                user.put("username", newUsername.isEmpty() ? currentUsername : newUsername);
                user.put("password", newPassword.isEmpty() ? user.get("password") : newPassword);
                found = true;
                break;
            }
        }

        if (found) {
            record.put("users", userlist);

            try (FileWriter file = new FileWriter(filepath)) {
                file.write(record.toJSONString());
                file.flush();
            }

            JOptionPane.showMessageDialog(this, "User updated successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "User not found or incorrect credentials.");
        }

    } catch (IOException | ParseException ex) {
        Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "An error occurred while updating.");
    }

    }//GEN-LAST:event_UpdatebuttonActionPerformed
 // Method to clear input fields when Clear button is clickedv
    private void ClearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbuttonActionPerformed
        // TODO add your handling code here:
        Cusernamefield.setText("");
        Cpasswordfeild.setText("");
        Npasswordfield.setText("");
        Nuserfeild.setText("");  
    }//GEN-LAST:event_ClearbuttonActionPerformed
// Method to go back to the Dashboard when Back button is clicke
    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
            // TODO add your handling code here:
        this.dispose();
        Dashboard e = new Dashboard();
        e.setVisible(true);
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void CusernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusernamefieldActionPerformed

    private void CpasswordfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpasswordfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpasswordfeildActionPerformed

    private void NuserfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuserfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuserfeildActionPerformed

    private void NpasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NpasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NpasswordfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }
public void filecheck() throws FileNotFoundException, IOException, ParseException { // Reads the JSON file and loads user data into the userlist array.
    FileReader reader = new FileReader(filepath);

    if (reader.ready()) {
        Scanner scan = new Scanner(reader);
        String line = "";
        while (scan.hasNext()) {
            line = line + scan.nextLine();
        }

        reader.close();

        if (!line.equals("")) {
            reader.close();
            FileReader reader2 = new FileReader(filepath);
            record = (JSONObject) jsonParser.parse(reader2);
            userlist = (JSONArray) record.get("users");
            reader2.close();
        }
    }

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Clearbutton;
    private javax.swing.JTextField Cpasswordfeild;
    private javax.swing.JTextField Cusernamefield;
    private javax.swing.JTextField Npasswordfield;
    private javax.swing.JTextField Nuserfeild;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
